# 指定环境语言
language: node_js

# 指定sudo权限
sudo: required

# 指定node版本
node_js: stable

# 指定缓存模块，缓存可以加速编译
cache:
    directories:
        - node_modules

# 邮件通知，这里配置不管成功或是失败都通知
notifications:
    email:
        recipients:
            - imcoddy+build@gmail.com
        on_success: change # default: change
        on_failure: always # default: always

# 构建的分支
branches:
    only:
        - develop

# 调整时区
before_install:
    - export TZ='Asia/Shanghai'

# 安装环境
install:
    - npm install -g gitbook-cli hexo-cli
    - npm install
    - gitbook install

# gitbook生成静态文件
script:
    # - gitbook build
    - hexo generate

# 发布静态文件
after_script:
    # - cp -r _book rebirth
    # - mv rebirth _book/
    # - cp robots.txt _book/
    # - cd ./_book
    - cd public
    - git init
    - git config user.name "imcoddy"
    - git config user.email "imcoddy@gmail.com"
    # - echo "metanet.press" > CNAME
    - git add .
    - git commit -m "Update Metanet.Press By TravisCI With Build $TRAVIS_BUILD_NUMBER"
    - git remote add origin https://${REPO}
    - git push --force --quiet "https://${GH_TOKEN}@${REPO}" master:gh-pages


# 环境变量
env:
    global:
        # Github Pages
        - REPO: github.com/imcoddy/metanet.press.git
