# 指定环境语言
language: node_js

# 指定sudo权限
sudo: required

# 指定node版本
node_js: 12

# 指定缓存模块，缓存可以加速编译
cache:
    directories:
        - node_modules

# 邮件通知，这里配置不管成功或是失败都通知
notifications:
    email:
        recipients:
            - imcoddy+build@gmail.com
        on_success: change # default: change
        on_failure: always # default: always

# 构建的分支
branches:
    only:
        - develop

# 调整时区
before_install:
    - export TZ='Asia/Shanghai'

# 安装环境
install:
    - npm install -g hexo-cli gulp
    - npm install

# 生成静态文件
script:
    - (cd rebirth ; git checkout gh-pages ; git pull origin gh-pages)
    - (cd themes/matery ; git pull origin develop)
    - hexo clean && gulp default

# 发布静态文件
after_script:
    - mv public blog
    - mkdir public
    - mv rebirth public
    - mv svskull public
    - mv blog public
    - cp deploy/* public/

    # - rsync -av rebirth/images/ public/images/
    # - rm -rf rebirth/images rebirth/rebirth
    # - mv rebirth public/
    - cd public
    - cp -R blog/images ./images
    - ln sitemap.xml baidusitemap.xml

    - git init
    - git config user.name "imcoddy"
    - git config user.email "imcoddy@gmail.com"
    # - echo "metanet.press" > CNAME
    - git add .
    - git commit -m "Update Metanet.Press By TravisCI With Build $TRAVIS_BUILD_NUMBER"
    - git remote add origin https://${REPO}
    - git push --force --quiet "https://${GH_TOKEN}@${REPO}" master:gh-pages

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   local_dir: public
#   on:
#     branch: develop

# 环境变量
env:
    global:
        # Github Pages
        - REPO: github.com/imcoddy/metanet.press.git
